---
- name: Ensure all services are available
  hosts: test
  gather_facts: yes
  become: yes
  vars:
    app_port: 3000
    app_host: "127.0.0.1"
    db_name: "postgres"
    db_host: "127.0.0.1"
    db_port: 5432
    postgres_user: postgres
    postgres_password: securepassword
    pg_database: postgres
    env_file_path: "/opt/stage_5b/.env"
  
  tasks:
    - name: Setup environment file
      template:
        src: templates/env.j2
        dest: /opt/stage_5b/.env
      vars:
        postgres_user: "{{ postgres_user }}"
        postgres_password: "{{ postgres_password }}"
        db_name: "{{ db_name }}"
        db_host: "{{ db_host }}"
        db_port: "{{ db_port }}"

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Start the application with PM2
      shell: |
        pm2 start /opt/stage_5b/dist/src/main.js --name "nestjsapp" --env production
    
    - name: Ensure Nginx service is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Check PostgreSQL service status
      command: systemctl is-active postgresql
      register: postgresql_status
      changed_when: false

    - name: Check Node.js application status
      command: lsof -i :{{ app_port }}
      register: nodejs_status
      changed_when: false

    - name: Check Nginx service status
      command: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Display PostgreSQL service status
      debug:
        msg: "PostgreSQL service is {{ postgresql_status.stdout }}"

    - name: Display Node.js application status
      debug:
        msg: "Node.js application status: {{ nodejs_status.stdout }}"

    - name: Display Nginx service status
      debug:
        msg: "Nginx service is {{ nginx_status.stdout }}"
