---
- name: Install and configure PostgreSQL
  hosts: hng
  become: true

  vars:
    pg_user: postgres
    pg_password: securepassword
    pg_password_file: /var/secrets/pg_pw.txt
    pg_database: postgres
    pg_host: localhost
    log_dir: /var/log/stage_5b
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name:
          - "postgresql"
          - "postgresql-client"
          - "postgresql-contrib"
        state: present

    - name: Ensure PostgreSQL service is enabled and started
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Ensure /var/secrets directory exists
      file:
        path: /var/secrets
        state: directory
        mode: '0700'

    - name: Save PostgreSQL credentials
      copy:
        dest: "{{ pg_password_file }}"
        content: "PG_USER={{ pg_user }}\nPG_PASSWORD={{ pg_password }}\nPG_DATABASE={{ pg_database }}\n"
        owner: root
        group: root
        mode: '0600'

    - name: Read PostgreSQL credentials
      slurp:
        src: "{{ pg_password_file }}"
      register: pg_creds

    - name: Set PostgreSQL credentials as variables
      set_fact:
        pg_user: "{{ (pg_creds.content | b64decode).split('\n')[0].split('=')[1] }}"
        pg_password: "{{ (pg_creds.content | b64decode).split('\n')[1].split('=')[1] }}"
        pg_database: "{{ (pg_creds.content | b64decode).split('\n')[2].split('=')[1] }}"