---
- name: Setup and Deploy NestJS Boilerplate
  hosts: hng
  become: yes
  
  tasks:
    - name: Install Node.js 20.16.0 LTS using NVM
      become: yes
      nvm:
        version: "20.16.0"
        state: present

    - name: Set Node.js 20.16.0 LTS as default
      become: yes
      nvm:
        version: "20.16.0"
        state: default
    
    - name: Install dependencies
      become_user: hng
      npm:
        path: /opt/stage_5b
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql-14
        state: present

    - name: Configure PostgreSQL
      become_user: postgres
      postgresql_db:
        name: stage_5b
        state: present

    - name: Save admin user and credentials
      copy:
        content: "hng:password"
        dest: /var/secrets/pg_pw.txt
        owner: hng
        group: hng
        mode: '0600'

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
    
    - name: Install Nginx 1.26
      apt:
        name: nginx=1.26*
        state: present

    - name: Setup Nginx to reverse proxy application to port 80
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx
      
    - name: Create log directory
      file:
        path: /var/log/stage_5b
        state: directory
        owner: hng
        group: hng

    - name: Configure stderr logging
      copy:
        content: ""
        dest: /var/log/stage_5b/error.log
        owner: hng
        group: hng

    - name: Configure stdout logging
      copy:
        content: ""
        dest: /var/log/stage_5b/out.log
        owner: hng
        group: hng

    
