---
- name: Configure an instance of the hng_boilerplate_nestjs project
  hosts: test
  become: true
  vars:
    repo_url: "https://github.com/hngprojects/hng_boilerplate_nestjs"
    branch: "devops"
    app_dir: "/opt/stage_5b"
    pg_admin_user: "admin"
    pg_admin_password: "devopsnext"
    pg_db: "hng_db"
    
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure hng user exists
      user:
        name: hng
        state: present
        create_home: yes

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes
      register: clone_result

    - name: Ensure the app directory is owned by hng user
      file:
        path: "{{ app_dir }}"
        owner: hng
        group: hng
        recurse: yes
      when: clone_result.after != clone_result.before


    - name: Install and configure PostgreSQL
      block:
        - name: Ensure PostgreSQL is running
          systemd:
            name: postgresql
            state: started
            enabled: yes

        - name: Set PostgreSQL admin user password
          become_user: postgres
          postgresql_user:
            name: "{{ pg_admin_user }}"
            password: "{{ pg_admin_password }}"
            role_attr_flags: "SUPERUSER,CREATEDB"

        - name: Create a database
          become_user: postgres
          postgresql_db:
            name: "{{ pg_db }}"
            owner: "{{ pg_admin_user }}"

        - name: Save PostgreSQL admin credentials
          copy:
            content: |
              POSTGRES_USER={{ pg_admin_user }}
              POSTGRES_PASSWORD={{ pg_admin_password }}
              POSTGRES_DB={{ pg_db }}
            dest: /var/secrets/pg_pw.txt
            owner: root
            group: root
            mode: '0600'

   