---
- name: Setup and Deploy NestJS Boilerplate
  hosts: test
  become: yes
  
  tasks:
    - name: clone the repository
      ansible.builtin.git:
        repo: https://github.com/hngprojects/hng_boilerplate_nestjs
        dest: /opt/stage_5b
        single_branch: yes
        version: devops

    - name: Install packages based on package.json
      community.general.npm:
        path: /opt/stage_5b

    - name: Install PostgreSQL
      apt:
        name: postgresql-14
        state: present

    - name: Configure PostgreSQL
      become_user: postgres
      postgresql_db:
        name: stage_5b
        state: present

    - name: Save admin user and credentials
      copy:
        content: "hng:password"
        dest: /var/secrets/pg_pw.txt
        owner: hng
        group: hng
        mode: '0600'

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
    
    - name: Install the version '1.26' of package "nginx" and allow potential downgrades
      ansible.builtin.apt:
        name: nginx=1.26
        state: present
        allow_downgrade: yes

    - name: Setup Nginx to reverse proxy application to port 80
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx
      
    - name: Create log directory
      file:
        path: /var/log/stage_5b
        state: directory
        owner: hng
        group: hng

    - name: Configure stderr logging
      copy:
        content: ""
        dest: /var/log/stage_5b/error.log
        owner: hng
        group: hng

    - name: Configure stdout logging
      copy:
        content: ""
        dest: /var/log/stage_5b/out.log
        owner: hng
        group: hng