---
- name: Installing rabbitMQ and Nginx services
  hosts: hng
  gather_facts: yes
  become: yes
  vars:
    rabbitmq_version: "3.8"
    hng_user: "hng"
    app_port: 3000
    app_host: "127.0.0.1"
    smtp_host: "smtp.gmail.com"  # Set your SMTP host here
    smtp_port: "587"
    smtp_user: "adesdorcas@gmail.com"
    smtp_password:
    rabbitmq_user: "mynextapp"
    rabbitmq_password: "nextrabbit"

  tasks:
    - name: Create stdout log file
      file:
        path: "{{ out_log }}"
        state: touch
        owner: "{{ hng_user }}"
        group: "{{ hng_user }}"
        mode: '0644'

    - name: Create stderr log file
      file:
        path: "{{ error_log }}"
        state: touch
        owner: "{{ hng_user }}"
        group: "{{ hng_user }}"
        mode: '0644'

    - name: Redirect stdout and stderr to log files
      shell: |
        exec > >(tee -a {{ out_log }} )
        exec 2> >(tee -a {{ error_log }} >&2 )
      args:
        executable: /bin/bash
      async: 0
      poll: 0

    - name: Install and configure RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: Enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Create RabbitMQ virtual host
      rabbitmq_vhost:
        name: my_vhost
        state: present

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: "{{ rabbitmq_user }}"
        password: "{{ rabbitmq_password }}"
        state: present
    
    - name: Set RabbitMQ user permissions
      rabbitmq_user:
        user: "{{ rabbitmq_user }}"
        vhost: my_vhost 
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: present

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
   