---
- name: Installing rabbitMQ and Nginx services
  hosts: hng
  gather_facts: yes
  become: yes
  vars:
    rabbitmq_version: "3.8"
    hng_user: "hng"
    app_port: 3000
    app_host: "127.0.0.1"
    smtp_host: "smtp.gmail.com"  # Set your SMTP host here
    smtp_port: "587"
    smtp_user: "adesdorcas@gmail.com"
    smtp_password:
    rabbitmq_user: "mynextapp"
    rabbitmq_password: "nextrabbit"

  tasks:
    - name: Create log directory
      file:
        path: /var/log/stage_5b
        state: directory
        owner: hng
        group: hng
        mode: '0755'

    - name: Create stdout log file
      file:
        path: /var/log/stage_5b/out.log
        state: touch
        owner: hng
        group: hng
        mode: '0644'

    - name: Create stderr log file
      file:
        path: /var/log/stage_5b/error.log
        state: touch
        owner: hng
        group: hng
        mode: '0644'
    
    - name: Configure systemd service for Node.js application
      copy:
        dest: /etc/systemd/system/stage_5b.service
        content: |
          [Unit]
          Description=Node.js Application

          [Service]
          ExecStart=/usr/bin/npm start --prefix /opt/stage_5b
          WorkingDirectory=/opt/stage_5b
          Restart=always
          User=hng
          Group=hng
          StandardOutput=append:/var/log/stage_5b/out.log
          StandardError=append:/var/log/stage_5b/error.log
          Environment=NODE_ENV=production

          [Install]
          WantedBy=multi-user.target
      notify: 
        - Reload systemd

    - name: Reload systemd
      systemd:
        daemon_reload: true

    - name: Ensure Node.js application is started
      systemd:
        name: stage_5b
        state: started
        enabled: yes

    - name: Install and configure RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: Enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Create RabbitMQ virtual host
      rabbitmq_vhost:
        name: my_vhost
        state: present

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: "{{ rabbitmq_user }}"
        password: "{{ rabbitmq_password }}"
        state: present
    
    - name: Set RabbitMQ user permissions
      rabbitmq_user:
        user: "{{ rabbitmq_user }}"
        vhost: my_vhost 
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: present

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
   